nodes: 1
tasks_per_node: 3
tag: ravdess_2-16x8x3
eval_name: pretrained_full_video_classification
data:
  dataset_val: 
    - /mnt/datasets/CREMA-D/additional/splits/split_0.csv
    - /mnt/datasets/CREMA-D/additional/splits/split_1.csv
    - /mnt/datasets/CREMA-D/additional/splits/split_2.csv
    - /mnt/datasets/CREMA-D/additional/splits/split_3.csv
    - /mnt/datasets/CREMA-D/additional/splits/split_4.csv
  num_classes: 8
  frames_per_clip: 16
  frame_step: 4
optimization:
  attend_across_segments: true
  resolution:  384
  batch_size: 12
pretrain:
  model_name: vit_huge
  checkpoint_key: target_encoder
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /mnt/slurm/lennart/jepaslt/models
  checkpoint: vith16-384.pth.tar
  write_tag: jepaslt_ravdess_2