name: jepaslt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - pyyaml
  - numpy
  - pandas
  - submitit
  - braceexpand
  - webdataset
  - timm
  - einops
  - beartype
  - ffmpeg
  - pip:
    - opencv-python
    - decord