nodes: 1
tasks_per_node: 3
tag: ravdess_3-16x8x3
eval_name: pretrained_full_video_classification
data:
  dataset_val: /mnt/datasets/RAVDESS/additional/splits/3_val.csv
  num_classes: 8
  frames_per_clip: 16
  frame_step: 4
optimization:
  attend_across_segments: true
  resolution:  384
  batch_size: 12
pretrain:
  model_name: vit_huge
  checkpoint_key: target_encoder
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /mnt/slurm/lennart/jepaslt/models
  checkpoint: vith16-384.pth.tar
  write_tag: jepaslt_ravdess_3